### PR TITLE
6: rust 1.74.1 update

### LINKED ISSUE #6: Feature request: 1.74.1
### Is your feature request related to a problem?

update for December patch

### Describe the solution to the problem

_No response_

### Describe the uses cases for the feature

_No response_

### Additional details

_No response_

### PR DESCRIPTION
**Pull request by jac18281828**
closes #6

### CODE REVIEW

**Comment by jac18281828** [comment]
https://blog.rust-lang.org/2023/12/07/Rust-1.74.1.html

**Review by insipx — APPROVED** [review]

**Review by neekolas — COMMENTED** [review]
All I see here is the CHANGELOG.md and not the actual version bump

**Comment by jac18281828** [comment]
> All I see here is the CHANGELOG.md and not the actual version bump

When the container is updated it will pull the version during the build.

**Comment by neekolas** [comment]
We should think about pinning versions so it doesn't get incidentally updated again later. I've run into nasty bugs with surprise Docker version updates by depending on the `latest` tag.

**Comment by jac18281828** [comment]
> We should think about pinning versions so it doesn't get incidentally updated again later. I've run into nasty bugs with surprise Docker version updates by depending on the `latest` tag.

We do pin to 'stable' but that does not require us to set the number.   I like the convenience of not having to change version numbers and simply rebuild the container.   I understand what you mean about potential versioning problems.   If we are not comfortable with 'latest' I have also tagged the release versions.  You can explore that here:

https://github.com/xmtp/rust/pkgs/container/rust

As this is a dev container I recommend using the latest version.   Everything is pinned to stable so this should give us the stable code with the latest security fixes.

**Comment by jac18281828** [comment]
For documentation purposes, the only way to trigger the build is to push a tag on this repo.  That should be a deliberate act and not something that would result in surprises.    That in particular is one of the reasons I've shared a pull request to update the version.  Everyone has a chance to build on latest, test and comment before we release.

**Pull request merged**
